# Generated by Django 2.1.5 on 2019-02-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UG_secondyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Roll_no', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Batch', models.CharField(blank=True, max_length=30, null=True)),
                ('Course', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
