# Generated by Django 2.1.5 on 2019-01-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
