# Generated by Django 2.1.5 on 2019-01-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
