# Generated by Django 2.1.5 on 2019-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Post', models.CharField(blank=True, max_length=30, null=True)),
                ('Intersts', models.CharField(blank=True, max_length=30, null=True)),
                ('Interestslist', models.TextField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Publications', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
